<a href="https://colab.research.google.com/github/Pongpang-2102/Text_Mining_and_Sentiment_Analytics_KDAI_projects/blob/main/KDAI_TMSA_Tutorial_EP11_SVD_Walk_Through_(1_Oct_23).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# https://machinelearningmastery.com/singular-value-decomposition-for-machine-learning/

In [ ]:
# SVD หรือ Singular-Value Decomposition คือ การแยกตัวประกอบของเมทริกซ์
# A = U . Sigma . V^T

# A : Input matrix
# U : Left singular vectors
# Sigma : Singular value หรือ diagonal matrix (เมทริกซ์ทแยงมุม)
# V : Right singular vectors

In [ ]:
from numpy import array
from scipy.linalg import svd

In [ ]:
A = array([[1, 2], [3, 4], [5, 6]])
print(A)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
A.shape

(3, 2)

In [ ]:
U, s, VT = svd(A)

In [ ]:
U

array([[-0.2298477 ,  0.88346102,  0.40824829],
       [-0.52474482,  0.24078249, -0.81649658],
       [-0.81964194, -0.40189603,  0.40824829]])

In [ ]:
U.shape

(3, 3)

In [ ]:
s

array([9.52551809, 0.51430058])

In [ ]:
s.shape

(2,)

In [ ]:
VT

array([[-0.61962948, -0.78489445],
       [-0.78489445,  0.61962948]])

In [ ]:
VT.shape

(2, 2)

In [ ]:
#  A = U . Sigma . V^T
# A (m x n)
# U (m x m) # Square matrix
# Sigma (m x n) ???
# VT (n x n)
A.shape, U.shape, s.shape, VT.shape

((3, 2), (3, 3), (2,), (2, 2))

In [ ]:
# สร้าง Matrix Sigma m x n

In [ ]:
from numpy import diag
from numpy import dot
from numpy import zeros

In [ ]:
Sigma = zeros((A.shape[0], A.shape[1]))
Sigma

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
Sigma.shape

(3, 2)

In [ ]:
# เอา s มาใส่ใน matrix 3 x 2


Sigma[:A.shape[1], :A.shape[1]] = diag(s)
Sigma

array([[9.52551809, 0.        ],
       [0.        , 0.51430058],
       [0.        , 0.        ]])

In [ ]:
# นำ Matrix ตัวประกอบคุณกันได้ matrix ใหม่ (B) เท่ากับ Input matrix (A)

In [ ]:
# A = U . Sigma . V^T
B = U.dot(Sigma.dot(VT))
B

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [ ]:
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
# แต่ถ้า m x n เป็น Square matrix จะสร้างเมทริกซ์ทแยงมุม ได้เลยโดยใช้ diag()

In [ ]:
A = array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

มี  3 เทอม  เปรียบเสมือนมี bag of word 3 คำ

In [ ]:
A.shape

(3, 3)

In [ ]:
U, s, VT = svd(A)

In [ ]:
s.shape

(3,)

In [ ]:
Sigma = diag(s)
Sigma

array([[1.68481034e+01, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 1.06836951e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 4.41842475e-16]])

In [ ]:
Sigma.shape

(3, 3)

In [ ]:
B = U.dot(Sigma.dot(VT))
B #ค่าที่ถูกประมาณ

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [ ]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# A = U . Sigma . V^T
# นำ Singular-Value Decomposition (SVD) มาประยุกต์ใช้กับ Topic Modeling อย่างไร

In [ ]:
# กำหนดให้ k คือ จำนวน Topic ที่เราเลือก
# B = U . Sigmak . V^Tk

# Sigmak คือ Matrix ที่ตัด Column ให้เหลือ k Column
# V^Tk คือ Matrix ที่ตัด Row ให้เหลือ k Row

In [ ]:
# T คือ Matix ที่ถูกลดมิติ
# T = U . Sigmak หรือ
# T = V^k . A

In [ ]:
A = array([
 [1,2,3,4,5,6,7,8,9,10],
 [11,12,13,14,15,16,17,18,19,20],
 [21,22,23,24,25,26,27,28,29,30]])
A

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])

In [ ]:
A.shape

(3, 10)

In [ ]:
U, s, VT = svd(A)

In [ ]:
U.shape, s.shape, VT.shape

((3, 3), (3,), (10, 10))

In [ ]:
Sigma = zeros((A.shape[0], A.shape[1]))
Sigma

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
Sigma.shape

(3, 10)

In [ ]:
s

array([9.69657342e+01, 7.25578339e+00, 5.43064394e-15])

In [ ]:
Sigma[:A.shape[0], :A.shape[0]] = diag(s)
Sigma

array([[9.69657342e+01, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 7.25578339e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 5.43064394e-15, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00]])

In [ ]:
# B = U . Sigmak . V^Tk

In [ ]:
n_elements = 2

In [ ]:
Sigma = Sigma[:, :n_elements] # signma จะตัดคอลัมน์ให้เหลือแค่ 2 คอลัมน์
Sigma

array([[96.96573419,  0.        ],
       [ 0.        ,  7.25578339],
       [ 0.        ,  0.        ]])

In [ ]:
Sigma.shape

(3, 2)

In [ ]:
VT = VT[:n_elements, :] #VT ตัดแถวให้เหลือแค่ 2 แถว
VT

array([[-0.24139304, -0.25728686, -0.27318068, -0.2890745 , -0.30496832,
        -0.32086214, -0.33675595, -0.35264977, -0.36854359, -0.38443741],
       [-0.53589546, -0.42695236, -0.31800926, -0.20906617, -0.10012307,
         0.00882003,  0.11776313,  0.22670623,  0.33564933,  0.44459242]])

In [ ]:
VT.shape

(2, 10)

In [ ]:
# ((3, 3), (3,), (10, 10)) เดิม

U.shape, Sigma.shape, VT.shape #ใหม่

((3, 3), (3, 2), (2, 10))

In [ ]:
B = U.dot(Sigma.dot(VT))
B

array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15., 16., 17., 18., 19., 20.],
       [21., 22., 23., 24., 25., 26., 27., 28., 29., 30.]])

In [ ]:
B.shape

(3, 10)

In [ ]:
A

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])

In [ ]:
T = U.dot(Sigma)
T

array([[-18.52157747,   6.47697214],
       [-49.81310011,   1.91182038],
       [-81.10462276,  -2.65333138]])

In [ ]:
T = A.dot(VT.T)
T

array([[-18.52157747,   6.47697214],
       [-49.81310011,   1.91182038],
       [-81.10462276,  -2.65333138]])

In [ ]:
T.shape

(3, 2)

In [ ]:
from sklearn.decomposition import TruncatedSVD

In [ ]:
svd = TruncatedSVD(n_components=2)
# Latent Semantic Analysis (LSA) -> svd

In [ ]:
svd.fit(A)

TruncatedSVD()

In [ ]:
result = svd.transform(A) # ตีความมว่าประโยค หรือกลุ่มคำที่เราเอามา มันใกล้ Topic (Cluster)  ไหน
# เลลขไหนมากที่สุด ใกล้ค่านั้นสุด
result

array([[18.52157747,  6.47697214],
       [49.81310011,  1.91182038],
       [81.10462276, -2.65333138]])

In [ ]:
result.shape

(3, 2)

In [ ]:
svd.components_.shape

(2, 10)

In [ ]:
svd.components_

array([[ 0.24139304,  0.25728686,  0.27318068,  0.2890745 ,  0.30496832,
         0.32086214,  0.33675595,  0.35264977,  0.36854359,  0.38443741],
       [-0.53589546, -0.42695236, -0.31800926, -0.20906617, -0.10012307,
         0.00882003,  0.11776313,  0.22670623,  0.33564933,  0.44459242]])

จะได้ว่ามี 2 topic -  ตีความว่าแต่ละ topic ใน 2  toic มีั bag of word หรืออยู่ใกล้ topic ไหนบ้าง

In [ ]:
VT.shape

(2, 10)

In [ ]:
VT

array([[-0.24139304, -0.25728686, -0.27318068, -0.2890745 , -0.30496832,
        -0.32086214, -0.33675595, -0.35264977, -0.36854359, -0.38443741],
       [-0.53589546, -0.42695236, -0.31800926, -0.20906617, -0.10012307,
         0.00882003,  0.11776313,  0.22670623,  0.33564933,  0.44459242]])

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive
